<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\UserBlog;
use Faker\Factory as Faker;
use Illuminate\Support\Facades\DB;

class BlogSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    
    public function run(): void
    {
        $faker = Faker::create();
        $categories = ['Mammal', 'Amphibian', 'Reptile', 'Avian'];

        // foreach(range(1, 20) as $index){
        //     DB::table('blogs')->insert([
        //     'species' => $faker->name(),
        //     'latin' => $faker->name(),
        //     'category' => $faker->randomElement($categories),
        //     'content' => $faker->text(200),
        //     'image' => $faker->imageUrl(200, 300, 'blogs', true, 'blog cover')
        //     ]);
        // }

        DB::table('blogs')->insert([
            ['species' => 'Galapagos Tortoise', 'latin' => 'Chelonoidis niger','category' => 'Reptile', 'content' => 'The Galápagos tortoise is a giant, herbivorous reptile native to the Galápagos Islands, known for its immense size, with some individuals weighing over 400 kg, and its extraordinary lifespan, often exceeding 100 years. These tortoises display unique adaptations, such as domed or saddleback shells, based on their specific island habitats and diets. They play a vital role in their ecosystem by dispersing seeds and shaping vegetation. Once heavily threatened by hunting and habitat destruction, conservation efforts have helped stabilize some populations, although several subspecies remain endangered. Famously linked to Charles Darwin\'s theory of evolution, the Galápagos tortoise is a powerful symbol of conservation and biodiversity.','image' => 'images/Tortoise.jpg'],
            ['species' => 'Lion', 'latin' => 'Panthera leo', 'category' => 'Mammal', 'content' => 'Lions are iconic big cats known for their strength, social behavior, and majestic appearance. They live in pride, typically of related females, their cubs, and a few dominant males. Native to the grasslands and savannas of Africa, lions are apex predators that primarily hunt large herbivores such as wildebeest, zebras, and buffalo. Male lions are distinguished by their thick, flowing manes, which serve as a sign of dominance and health. Lions are keystone species, playing a crucial role in regulating prey populations and maintaining ecosystem balance.', 'image' => 'images/Lion.jpg'],
            ['species' => 'Tiger', 'latin' => 'Panthera tigris', 'category' => 'Mammal', 'content' => 'Tigers are the largest members of the cat family and are renowned for their striking orange coats marked with black stripes. Native to Asia, they inhabit diverse environments ranging from tropical rainforests to cold, snowy taigas. Tigers are solitary and territorial, relying on stealth and immense power to ambush prey such as deer and wild boar. They are strong swimmers and often use water to cool off. Tigers are endangered, with population declines driven by habitat loss, poaching, and human-wildlife conflict, making conservation efforts critical for their survival.', 'image' => 'images/Tiger.jpg'],
            ['species' => 'Elephant', 'latin' => 'Loxodonta africana', 'category' => 'Mammal', 'content' => 'African elephants are the largest land animals on Earth, recognized by their massive size, large ears, and long tusks. These intelligent and social animals live in matriarchal herds, led by the oldest female. Elephants are essential to their ecosystems, as they shape landscapes by uprooting trees and creating water holes. They have remarkable memories and form close familial bonds. Despite their size, elephants face significant threats from poaching for ivory and habitat destruction. Conservation programs aim to protect these gentle giants and ensure their long-term survival.', 'image' => 'images/Elephant.jpg'],
            ['species' => 'Gray Wolf', 'latin' => 'Canis lupus', 'category' => 'Mammal', 'content' => 'Gray wolves are highly adaptable and social predators found across North America, Europe, and Asia. They live in structured packs with complex hierarchies, relying on teamwork to hunt large prey such as elk and moose. Wolves play a vital role in maintaining healthy ecosystems by controlling herbivore populations. Their haunting howls are used for communication within the pack and to signal their presence to rival groups. Although wolves were once extensively hunted, conservation efforts have helped some populations recover, though they still face threats from habitat loss and human conflict.', 'image' => 'images/Wolf.jpg'],
            ['species' => 'Giraffe', 'latin' => 'Giraffa camelopardalis', 'category' => 'Mammal', 'content' => 'Giraffes are the tallest land animals, capable of reaching heights up to 5.5 meters (18 feet). Their long necks allow them to access leaves high in the canopy, giving them a competitive edge in savanna ecosystems. Native to Africa, giraffes are peaceful herbivores that spend much of their time grazing on acacia trees. Their unique spotted patterns help with camouflage, and their long legs enable them to run at speeds of up to 35 mph when threatened. Giraffe populations are declining due to habitat loss and poaching, making conservation efforts crucial.', 'image' => 'images/Giraffe.jpg'],
            ['species' => 'Polar Bear', 'latin' => 'Ursus maritimus', 'category' => 'Mammal', 'content' => 'Polar bears are apex predators of the Arctic, relying on sea ice to hunt seals. They have thick fur and a layer of fat to insulate against the cold. Polar bears are excellent swimmers, capable of traveling long distances in search of food. Climate change poses the greatest threat to their survival as rising temperatures reduce sea ice, limiting their hunting grounds and breeding areas.', 'image' => 'images/PolarBear.jpg'],
            ['species' => 'Kangaroo', 'latin' => 'Macropus rufus', 'category' => 'Mammal', 'content' => 'Red kangaroos are the largest marsupials, endemic to Australia. Their strong hind legs allow them to hop at high speeds, covering large distances. Kangaroos live in groups called mobs and are herbivores, grazing on grasses and shrubs. Females carry their joeys in a pouch until they are old enough to survive independently. Kangaroos are iconic symbols of Australia, yet they face challenges from droughts and habitat destruction.', 'image' => 'images/Kangaroo.jpg'],
            ['species' => 'Orangutan', 'latin' => 'Pongo pygmaeus', 'category' => 'Mammal', 'content' => 'Orangutans are great apes native to Borneo and Sumatra, spending most of their time in trees. Known for their reddish-brown fur and high intelligence, they use tools and build nests for sleeping. Orangutans have a slow reproductive rate, with females giving birth only once every 6-8 years. Deforestation and illegal wildlife trade pose severe threats to their survival, placing them on the critically endangered list.', 'image' => 'images/Orangutan.jpg'],
            ['species' => 'Dolphin', 'latin' => 'Tursiops truncatus', 'category' => 'Mammal', 'content' => 'Bottlenose dolphins are highly intelligent marine mammals, known for their playful behavior and complex social structures. They use echolocation to navigate and hunt for fish. Dolphins are found in oceans worldwide and often interact with humans. Pollution, fishing nets, and habitat degradation are significant threats to dolphin populations.', 'image' => 'images/Dolphin.jpg'],
            ['species' => 'Hippopotamus', 'latin' => 'Hippopotamus amphibius', 'category' => 'Mammal', 'content' => 'Hippos are large, semi-aquatic mammals found in African rivers and lakes. They spend most of their day submerged to stay cool, emerging at night to graze. Despite their herbivorous diet, hippos are aggressive and can be dangerous. Hippos play a crucial role in their ecosystem by creating paths in water bodies and fertilizing the land. They are threatened by poaching and habitat loss.', 'image' => 'images/Hippo.jpg'],
            ['species' => 'Chimpanzee', 'latin' => 'Pan troglodytes', 'category' => 'Mammal', 'content' => 'Chimpanzees are highly intelligent primates and are one of humans’ closest living relatives, sharing approximately 98% of our DNA. Native to the forests and savannas of West and Central Africa, chimpanzees live in large social groups called troops. They are omnivores, with a diet consisting of fruits, leaves, insects, and occasionally small animals. Chimpanzees are known for their use of tools, such as sticks for extracting termites from mounds, and stones for cracking nuts. They communicate using vocalizations, gestures, and facial expressions. However, chimpanzees face threats from habitat destruction, poaching, and the illegal pet trade, leading to a decline in their populations.', 'image' => 'images/Chimpanzee.jpg'],
            ['species' => 'Gorilla', 'latin' => 'Gorilla gorilla', 'category' => 'Mammal', 'content' => 'Gorillas are the largest primates, native to the tropical forests of Africa. They live in social groups led by a dominant silverback male. Gorillas are primarily herbivorous, feeding on leaves, fruits, and stems. Highly intelligent, gorillas are known to use tools and display emotions such as grief and joy. Despite their strength and size, gorillas are gentle creatures. However, they face critical threats from poaching, habitat destruction, and diseases, placing them on the endangered species list.', 'image' => 'images/Gorilla.jpg'],
            ['species' => 'Cheetah', 'latin' => 'Acinonyx jubatus', 'category' => 'Mammal', 'content' => 'Cheetahs are the fastest land animals, capable of reaching speeds up to 60-70 mph in short bursts while chasing prey. Found in Africa and parts of Iran, cheetahs inhabit open plains and savannas. Unlike other big cats, cheetahs are lightweight with a slender build, which enhances their speed and agility. They primarily hunt small to medium-sized ungulates. Cheetahs face severe threats from habitat loss, human conflict, and low genetic diversity, making them vulnerable to extinction.', 'image' => 'images/Cheetah.jpg'],
            ['species' => 'Brown Bear', 'latin' => 'Ursus arctos', 'category' => 'Mammal', 'content' => 'Brown bears are large, powerful mammals found across North America, Europe, and Asia. They are omnivores, feeding on berries, fish, small mammals, and insects. Brown bears are known for their impressive strength and ability to stand on their hind legs to survey their surroundings. They hibernate during winter, relying on fat reserves accumulated during summer. Although their populations are stable in some areas, habitat loss and human-wildlife conflict pose ongoing threats to their survival.', 'image' => 'images/BrownBear.jpg'],
            ['species' => 'Zebra', 'latin' => 'Equus quagga', 'category' => 'Mammal', 'content' => 'Zebras are known for their distinctive black-and-white stripes, which serve as camouflage and a deterrent against predators. They inhabit grasslands and savannas across Africa, living in herds to increase their chances of survival. Zebras graze alongside other herbivores, playing a vital role in maintaining the ecosystem. Habitat fragmentation and hunting pose threats to zebra populations.', 'image' => 'images/Zebra.jpg'],
            ['species' => 'Axolotl', 'latin' => 'Ambystoma mexicanum','category' => 'Amphibian', 'content' => 'The Axolotl is a fascinating aquatic salamander native to Mexico, primarily found in lakes such as Lake Xochimilco. It is known for its extraordinary ability to regenerate limbs, spinal cords, and even parts of its heart and brain. Unlike most Amphibian, the Axolotl retains its larval features throughout its life, a condition called neoteny. Its external gills, which resemble feathery tufts, allow it to breathe underwater. Unfortunately, the Axolotl is critically endangered due to habitat loss and pollution, although it thrives in captivity and is a popular subject in scientific research.', 'image' => 'images/Axolotl.jpg'],
            ['species' => 'Olm', 'latin' => 'Proteus anguinus','category' => 'Amphibian', 'content' => 'The Olm is a blind, cave-dwelling salamander found in the subterranean waters of southeastern Europe. Adapted to its dark environment, it has no functional eyes and relies on smell and vibration detection. Olms can live for over 100 years and can survive without food for up to a decade. They are an endangered species due to habitat destruction.', 'image' => 'images/Olm.jpg'],
            ['species' => 'Goliath Frog', 'latin' => 'Conraua goliath','category' => 'Amphibian', 'content' => 'The Goliath Frog is the largest frog species, native to rivers and waterfalls in central Africa. It can grow up to 13 inches in length and weigh over 7 pounds. Despite its size, the Goliath Frog has a surprisingly delicate touch when constructing nests. It feeds on insects, crustaceans, and even small vertebrates. Habitat destruction and hunting have led to its vulnerable status.', 'image' => 'images/GoliathFrog.jpg'],
            ['species' => 'Red-Eyed Tree Frog', 'latin' => 'Agalychnis callidryas','category' => 'Amphibian', 'content' => 'The Red-Eyed Tree Frog is an arboreal species native to Central America. It is instantly recognizable by its vivid red eyes, green body, and bright blue and yellow flanks. These frogs are nocturnal and rely on their vibrant coloration to startle predators when threatened. They are excellent climbers, using their adhesive toe pads to navigate leaves and branches. The species plays an essential role in its ecosystem as both predator and prey, feeding on insects and being hunted by snakes, birds, and other larger animals.', 'image' => 'images/RedEyedFrog.jpg'],
            ['species' => 'African Bullfrog', 'latin' => 'Pyxicephalus adspersus','category' => 'Amphibian', 'content' => 'The African Bullfrog is one of the largest frog species in the world, native to southern Africa. Males can reach sizes of over 9 inches and weigh more than 2 pounds. These frogs are highly territorial and can be aggressive, especially during breeding season. They are carnivorous and have a varied diet, including insects, small birds, and even other frogs. Males are notable for their parental care, guarding their tadpoles and even digging channels to connect drying ponds to ensure their survival.', 'image' => 'images/AfricanBullfrog.jpg'],
            ['species' => 'Poison Dart Frog', 'latin' => 'Dendrobates tinctorius','category' => 'Amphibian', 'content' => 'The Poison Dart Frog is a small, brightly colored frog native to the rainforests of Central and South America. Its vivid coloration serves as a warning to predators of its toxicity, which comes from the alkaloids in its skin. Indigenous tribes have historically used the frog\'s toxins to coat blow darts for hunting. These frogs feed primarily on ants and mites, which contribute to their toxic properties. In captivity, where their diet differs, they lose their toxicity.', 'image' => 'images/PoisonDart.jpg'],
            ['species' => 'Hellbender', 'latin' => 'Cryptobranchus alleganiensis','category' => 'Amphibian', 'content' => 'The Hellbender is a giant aquatic salamander found in fast-flowing streams of North America. Reaching lengths of up to 30 inches, it is one of the largest salamanders in the world. Hellbenders are nocturnal and use loose skin folds along their bodies to absorb oxygen from the water. They primarily feed on crayfish and small fish. This species is a key indicator of water quality, as it requires clean, well-oxygenated streams to survive.', 'image' => 'images/Hellbender.jpg'],
            ['species' => 'Chinese Giant Salamander', 'latin' => 'Andrias davidianus','category' => 'Amphibian', 'content' => 'The Chinese Giant Salamander is the largest amphibian ,species, capable of growing up to 6 feet in length. Endemic to China, it lives in cool, fast-moving streams and lakes. This nocturnal species preys on fish, insects, and crustaceans. It has poor eyesight and relies on sensory nodes on its head to detect vibrations in the water. Sadly, it is critically endangered due to habitat destruction, pollution, and overexploitation for its meat and use in traditional medicine.', 'image' => 'images/GiantSalamander.jpg'],
            ['species' => 'Fire Salamander', 'latin' => 'Salamandra salamandra','category' => 'Amphibian', 'content' => 'The Fire Salamander is a striking amphibian with black skin marked by yellow or orange patches, found in forests across Europe. It is primarily nocturnal and prefers damp environments. The Fire Salamander secretes toxins from its skin as a defense mechanism, which can irritate predators. It is viviparous, meaning it gives birth to live young, a unique trait among Amphibian.', 'image' => 'images/FireSalamander.jpg'],
            ['species' => 'Eastern Newt', 'latin' => 'Notophthalmus viridescens','category' => 'Amphibian', 'content' => 'The Eastern Newt is a common amphibian in North America, with a complex life cycle that includes aquatic larva, terrestrial juvenile (red eft), and aquatic adult stages. The bright orange-red coloration of the juvenile stage serves as a warning to predators of its toxicity. Eastern Newts are adaptable and thrive in a variety of freshwater habitats, feeding on small invertebrates.', 'image' => 'images/Newt.jpg'],
            ['species' => 'European Common Frog', 'latin' => 'Rana temporaria','category' => 'Amphibian', 'content' => 'The European Common Frog is a widespread species found across Europe in damp habitats like ponds, marshes, and grasslands. It has smooth, variable-colored skin that ranges from green to brown, often with dark blotches. These frogs hibernate in the winter, either in mud or underwater. Their diet consists mainly of insects, slugs, and worms.', 'image' => 'images/EuropeanFrog.jpg'],
            ['species' => 'Cane Toad', 'latin' => 'Rhinella marina','category' => 'Amphibian', 'content' => 'The Cane Toad is a large, invasive species native to Central and South America but introduced to other regions, such as Australia, to control agricultural pests. Unfortunately, its introduction has caused ecological harm, as it preys on native species and outcompetes local Amphibian. It secretes a potent toxin from its skin that can be lethal to predators.', 'image' => 'images/CaneToad.jpg'],
            ['species' => 'Tiger Salamander', 'latin' => 'Ambystoma tigrinum','category' => 'Amphibian', 'content' => 'The Tiger Salamander is a large and colorful amphibian native to North America. It is named for its yellow and black striped pattern. These salamanders are secretive and spend most of their lives underground, emerging during rainy seasons to breed. They are opportunistic feeders, consuming insects, worms, and small vertebrates.', 'image' => 'images/TigerSalamander.jpg'],
            ['species' => 'Wood Frog', 'latin' => 'Lithobates sylvaticus','category' => 'Amphibian', 'content' => 'The Wood Frog is known for its remarkable ability to survive freezing temperatures. Found in North America, it produces special proteins that act as antifreeze, allowing it to hibernate in a frozen state during winter. Once thawed, it resumes normal activity. Wood Frogs breed explosively in early spring, laying eggs in temporary pools before they dry up.', 'image' => 'images/WoodFrog.jpg'],
            ['species' => 'Glass Frog', 'latin' => 'Hyalinobatrachium valerioi','category' => 'Amphibian', 'content' => 'The Glass Frog is an arboreal species found in Central and South America, known for its translucent skin, which makes its internal organs visible. These frogs inhabit forest canopies near streams, where they lay eggs on leaves overhanging water. Males guard the eggs until they hatch and drop into the water.', 'image' => 'images/GlassFrog.jpg'],
            ['species' => 'Bald Eagle', 'latin' => 'Haliaeetus leucocephalus','category' => 'Avian', 'content' => 'The Bald Eagle is a powerful bird of prey and the national symbol of the United States, representing freedom and strength. With a wingspan of up to 7.5 feet, it is one of the largest raptors in North America. Found near large bodies of water, it prefers habitats with abundant fish and tall trees for nesting. Bald Eagles are skilled hunters, often swooping down to snatch fish from the water’s surface, but they are also opportunistic scavengers. Their massive nests, called eyries, can reach up to 10 feet wide and weigh over a ton. Despite once being endangered, conservation efforts have helped their populations recover significantly', 'image' => 'images/BaldEagle.jpg'],
            ['species' => 'Peregrine Falcon', 'latin' => 'Falco peregrinus','category' => 'Avian', 'content' => 'The Peregrine Falcon holds the title of the fastest animal on Earth, capable of diving at speeds exceeding 240 mph during hunting stoops. This agile predator is found on every continent except Antarctica, often nesting on cliffs or urban skyscrapers. Peregrines primarily prey on medium-sized birds, such as pigeons and doves, capturing them mid-flight with incredible precision. They have a distinctive black "mustache" marking on their faces and sharp talons for killing prey. Once endangered due to pesticide use, they are now a conservation success story', 'image' => 'images/Peregrine.jpg'],
            ['species' => 'Scarlet Macaw', 'latin' => 'Ara macao','category' => 'Avian', 'content' => 'The Scarlet Macaw is a large, vividly colored parrot native to the tropical rainforests of Central and South America. With its vibrant red, yellow, and blue plumage, it is one of the most iconic symbols of the Amazon rainforest. These intelligent birds have strong beaks for cracking nuts and seeds and are known for their loud, raucous calls, which can travel long distances. They form lifelong pair bonds and are highly social, often seen in small flocks. Scarlet Macaws play a vital role in their ecosystem by dispersing seeds, promoting forest regeneration', 'image' => 'images/ScarletMacaw.jpg'],
            ['species' => 'European Robin', 'latin' => 'Erithacus rubecula','category' => 'Avian', 'content' => 'The European Robin is a small, round bird with an iconic red breast and a cheerful, melodious song. It is a year-round resident in Europe, thriving in gardens, woodlands, and hedgerows. Robins are territorial and often seen flitting close to humans, especially during gardening, as they hunt for insects and worms unearthed by human activity. In winter, they supplement their diet with berries and seeds. Known for their friendly demeanor, robins are deeply embedded in European folklore and often associated with Christmas', 'image' => 'images/EuropeanRobin.jpg'],
            ['species' => 'Emperor Penguin', 'latin' => 'Aptenodytes forsteri','category' => 'Avian', 'content' => 'The Emperor Penguin is the tallest and heaviest of all penguin species, standing up to 4 feet tall and weighing up to 90 pounds. Native to Antarctica, it endures one of the harshest climates on Earth, with temperatures dropping below -50°F. During winter, males incubate eggs on their feet under a special brood pouch for up to 2 months, fasting during this time. Females return with food after foraging in the ocean. Emperor Penguins can dive to depths of over 500 meters and hold their breath for more than 20 minutes while hunting for fish, squid, and krill.', 'image' => 'images/EmperorPenguin.jpg'],
            ['species' => 'Northern Cardinal', 'latin' => 'Cardinalis cardinalis','category' => 'Avian', 'content' => 'The Northern Cardinal is a striking songbird known for its bright red plumage in males and warm brownish-red tones in females. Found across North and Central America, it inhabits woodlands, gardens, and shrubby areas. Cardinals are non-migratory, remaining in their territories year-round. They are known for their rich, whistling songs, which both males and females use to communicate. Cardinals feed on seeds, fruits, and insects, using their strong beaks to crack open tough shells. Their vibrant appearance and melodious song make them a favorite among birdwatchers.', 'image' => 'images/NorthernCardinal.jpg'],
            ['species' => 'Great Horned Owl', 'latin' => 'Bubo virginianus','category' => 'Avian', 'content' => 'The Great Horned Owl is a formidable nocturnal predator, instantly recognizable by its "horned" feather tufts and piercing yellow eyes. It is one of the most widespread owls in the Americas, thriving in diverse habitats from forests to deserts. This owl is an apex predator, preying on a wide range of animals, including rodents, birds, and even skunks. With a powerful grip and silent flight, it is a stealthy hunter. The Great Horned Owl\'s haunting hoots are a familiar sound in the night.', 'image' => 'images/GreatHornedOwl.jpg'],
            ['species' => 'Blue Jay', 'latin' => 'Cyanocitta cristata','category' => 'Avian', 'content' => 'The Blue Jay is a bold, intelligent bird found in North America, easily identified by its bright blue feathers, black necklace, and noisy calls. These birds are known for their complex social behavior and mimicry skills, often imitating the calls of hawks. Blue Jays are highly adaptable, thriving in forests, suburban areas, and even urban parks. They feed on seeds, nuts, and insects, often caching food for later use. Blue Jays play a crucial role in spreading acorns, aiding oak tree growth.', 'image' => 'images/Bluejay.jpg'],
            ['species' => 'American Flamingo', 'latin' => 'Phoenicopterus ruber','category' => 'Avian', 'content' => 'The American Flamingo is a tall, wading bird with bright pink feathers, long legs, and a distinctive curved beak. Its coloration comes from carotenoids in its diet, which includes algae, shrimp, and small invertebrates. Flamingos are highly social, forming colonies that can number in the thousands. They perform synchronized group displays during courtship. Found in shallow lagoons and salt flats of the Caribbean and coastal South America, flamingos are known for their unique "filter-feeding" technique.', 'image' => 'images/Flamingo.jpg'],
            ['species' => 'Golden Pheasant', 'latin' => 'Chrysolophus pictus','category' => 'Avian', 'content' => 'The Golden Pheasant is a brilliantly colored bird native to the forests of western China. Males are renowned for their dazzling golden crest, red body, and green plumage, while females are more subdued in color. These birds are shy and ground-dwelling, feeding on seeds, grains, and insects. Golden Pheasants are often kept in aviaries for their beauty and are symbols of good fortune in Chinese culture.', 'image' => 'images/GoldenPheasant.jpg'],
            ['species' => 'Kingfisher', 'latin' => 'Alcedo atthis','category' => 'Avian', 'content' => 'The Kingfisher is a small, brightly colored bird known for its exceptional fishing skills. Found near rivers, streams, and ponds, it dives into water with precision to catch fish. Kingfishers have excellent vision, including the ability to compensate for water refraction when hunting. Their nests are burrowed into riverbanks.', 'image' => 'images/Kingfisher.jpg'],
            ['species' => 'Andean Condor', 'latin' => 'Vultur gryphus','category' => 'Avian', 'content' => 'The Andean Condor is one of the largest flying birds, with a wingspan of up to 10 feet. Found in the Andes Mountains of South America, it is a symbol of power and freedom in Andean culture. A scavenger, it feeds on carrion, soaring high altitudes for hours in search of food.', 'image' => 'images/AndeanCondor.jpg'],
            ['species' => 'Snowy Owl', 'latin' => 'Bubo scandiacus','category' => 'Avian', 'content' => 'The Snowy Owl is a stunning Arctic bird with thick white feathers to insulate it against freezing temperatures. Known for its silent flight and keen hunting skills, it preys on small mammals like lemmings. Snowy Owls are nomadic, moving based on prey availability.', 'image' => 'images/SnowOwl.jpg'],
            ['species' => 'Red-tailed Hawk', 'latin' => 'Buteo jamaicensis','category' => 'Avian', 'content' => 'The Red-tailed Hawk is a versatile bird of prey with a reddish-brown tail and sharp talons. It is found across North America in various habitats, from deserts to forests. It primarily feeds on rodents, using its keen eyesight to spot prey from great heights.', 'image' => 'images/RedTailHawk.jpg'],
            ['species' => 'Atlantic Puffin', 'latin' => 'Fratercula arctica', 'category' => 'Avian', 'content' => 'The Atlantic Puffin is a seabird known for its colorful beak and waddling gait. Found along the coasts of the North Atlantic, it nests in burrows on cliffs. Puffins are excellent swimmers, using their wings to "fly" underwater while catching fish.', 'image' => 'images/Puffin.jpg'],
            ['species' => 'Alligator Snapping Turtle', 'latin' => 'Macrochelys temminckii','category' => 'Reptile', 'content' => 'The alligator snapping turtle is a large, freshwater turtle native to rivers, lakes, and swamps in the southeastern United States. Known for its rugged appearance, it features a spiked, ridged shell, a powerful beak-like jaw, and a worm-shaped lure on its tongue used to attract prey. It is one of the largest freshwater turtles, with adults often weighing over 80 kg (175 lbs). Primarily carnivorous, it feeds on fish, Amphibian, and even smaller turtles. This species is long-lived, with lifespans reaching 50–100 years in the wild. Though formidable in appearance, alligator snapping turtles face threats from habitat loss, pollution, and overharvesting, leading to their classification as a vulnerable species in need of conservation efforts.','image' => 'images/SnappingTurtle.jpg'],     
            ['species' => 'Green Sea Turtle', 'latin' => 'Chelonia mydas','category' => 'Reptile', 'content' => 'The green sea turtle is a large marine reptile found in tropical and subtropical oceans worldwide. Known for its smooth, heart-shaped shell and paddle-like flippers, it is named for the greenish color of its body fat, which results from its herbivorous diet of seagrasses and algae. Adult green sea turtles can grow up to 1.5 meters (5 feet) in length and weigh over 230 kg (500 lbs). They are migratory, traveling long distances between feeding grounds and nesting beaches, where females lay eggs in sandy nests. Despite their cultural and ecological importance, green sea turtles face numerous threats, including habitat loss, climate change, pollution, and poaching, leading to their status as an endangered species. Conservation efforts focus on protecting nesting sites and reducing bycatch in fisheries to ensure their survival.','image' => 'images/SeaTurtle.jpg'],
            ['species' => 'Veiled Chameleon', 'latin' => 'Chamaeleo calyptratus','category' => 'Reptile', 'content' => 'Chameleons are a unique group of reptiles known for their incredible ability to change color, long sticky tongues, and independently rotating eyes. They are primarily found in sub-Saharan Africa and Madagascar, with some species in parts of the Middle East, southern Europe, and Asia. Chameleons range in size from just a few centimeters, like the tiny Brookesia chameleons, to over half a meter, such as the Parson\'s chameleon. Their color-changing ability is used for communication, camouflage, and temperature regulation, controlled by specialized skin cells called chromatophores. Chameleons are arboreal, spending most of their time in trees, and their zygodactylous feet and prehensile tails aid in climbing. They are primarily insectivorous, using their projectile tongues to catch prey with precision. While some species are common, habitat loss, climate change, and the pet trade threaten many chameleon populations, highlighting the need for conservation efforts.','image' => 'images/Chameleon.jpg'],
            ['species' => 'House Gecko', 'latin' => 'Hemidactylus frenatus','category' => 'Reptile', 'content' => 'The house gecko is a small, nocturnal lizard commonly found in warm regions across the globe, often living in close proximity to humans. These geckos are known for their adaptability, thriving in urban environments and feeding on insects attracted to artificial lights. Typically light gray or tan in color, house geckos have a slender body, large eyes adapted for night vision, and adhesive toe pads that allow them to climb walls and ceilings with ease. They play a beneficial role in controlling pest populations, making them a welcome presence in many households. While several species are called "house geckos," the most widespread is the Hemidactylus frenatus, also known as the common house gecko. Despite their resilience, habitat changes and invasive species can sometimes challenge their populations.','image' => 'images/Gecko.jpg'],
            ['species' => 'Komodo Dragon', 'latin' => 'Varanus komodoensis','category' => 'Reptile', 'content' => 'The Komodo dragon is the largest living species of lizard, native to a few Indonesian islands, including Komodo, Rinca, Flores, and Gili Motang. These massive reptiles can grow up to 3 meters (10 feet) in length and weigh over 70 kg (150 lbs). Known for their muscular build, sharp claws, and powerful tails, Komodo dragons are apex predators, feeding on a wide variety of prey, including deer, pigs, and even water buffalo. They use a combination of stealth, speed, and their sharp, serrated teeth to take down prey, along with venomous saliva containing toxins that inhibit blood clotting and cause shock. Komodo dragons are also scavengers, with their keen sense of smell allowing them to detect carrion from several kilometers away. Despite their fearsome reputation, they are vulnerable to threats such as habitat loss, poaching, and human-wildlife conflict, leading to their classification as an endangered species. Conservation programs in Komodo National Park and surrounding areas are crucial to preserving these iconic reptiles and their unique ecosystems.','image' => 'images/Komodo.jpg'],           
            ['species' => 'Anaconda', 'latin' => 'Eunectes murinus','category' => 'Reptile', 'content' => 'The anaconda, particularly the green anaconda (Eunectes murinus), is one of the largest and most powerful snakes in the world, native to the wetlands and rainforests of South America. Known for its impressive size, it can grow over 9 meters (30 feet) long and weigh up to 250 kg (550 lbs). Anacondas are non-venomous constrictors, using their muscular bodies to ambush and subdue prey such as fish, birds, and mammals. Primarily aquatic, they are excellent swimmers and often reside in slow-moving rivers and swamps. Despite their fearsome reputation, they play an important role in their ecosystem by regulating the populations of other species.','image' => 'images/Anaconda.jpg'],
            ['species' => 'King Cobra', 'latin' => 'Ophiophagus hannah','category' => 'Reptile', 'content' => 'The king cobra is the longest venomous snake in the world, reaching lengths of up to 5.6 meters (18.5 feet). Native to forests and jungles across Southeast Asia, it is known for its distinctive hood, which it expands when threatened, making it an intimidating presence. Unlike many other snakes, the king cobra primarily preys on other snakes, including venomous species, and has specialized venom that targets the nervous system, allowing it to immobilize its prey quickly. Despite its fearsome reputation, the king cobra is generally shy and avoids human contact, but it can become highly defensive if threatened. Conservation efforts are important, as habitat loss and human-wildlife conflict pose significant threats to their populations.','image' => 'images/Cobra.jpg'],
            ['species' => 'Western Diamondback Rattlesnake', 'latin' => 'Crotalus atrox','category' => 'Reptile', 'content' => 'The western diamondback rattlesnake is a venomous snake found in the United States, primarily in the southwestern and southeastern regions. Known for its distinctive diamond-shaped pattern on its back and the rattle at the end of its tail, which it uses as a warning, the diamondback can grow up to 2.4 meters (8 feet) long. It is an ambush predator, relying on its camouflage to blend into its surroundings while waiting for prey, such as small mammals, birds, and reptiles. The snake\'s venom is a potent mixture of hemotoxins, which cause tissue damage and disrupt blood clotting. Despite its fearsome reputation, diamondback rattlesnakes generally avoid humans unless provoked. They are an important part of their ecosystem, helping control rodent populations.','image' => 'images/Rattlesnake.jpg'],
            ['species' => 'Nile Crocodile', 'latin' => 'Crocodylus niloticus','category' => 'Reptile', 'content' => 'The Nile crocodile is one of the largest and most aggressive crocodile species, found throughout sub-Saharan Africa, primarily in freshwater rivers, lakes, and marshes. It can grow up to 5 meters (16 feet) in length and weigh over 1,000 kg (2,200 lbs), making it one of the most formidable predators in Africa. Known for its powerful bite and stealthy hunting techniques, the Nile crocodile preys on a wide range of animals, including fish, birds, and mammals, often ambushing its prey from the water. While generally solitary, they can become highly social, especially during the mating season. Despite their fearsome nature, Nile crocodiles face threats from habitat loss and hunting. They are classified as a species of "Least Concern," but localized populations are vulnerable.','image' => 'images/Crocodile.jpg'],
            ['species' => 'American Alligator', 'latin' => 'Alligator mississippiensis','category' => 'Reptile', 'content' => 'The American alligator is a large reptile native to the southeastern United States, commonly found in freshwater habitats like rivers, lakes, swamps, and marshes. Adult alligators typically range from 3 to 4 meters (10 to 13 feet) in length, with males growing larger than females. Recognizable by their broad, rounded snouts and dark greenish-gray coloration, they are apex predators in their ecosystems. American alligators primarily feed on fish, birds, and mammals, using their powerful jaws to capture and crush prey. Despite their fearsome reputation, they play a crucial role in controlling the populations of other species and maintaining the balance of wetland ecosystems. Once endangered due to hunting for their hides, conservation efforts have helped their populations recover, and they are now considered a species of "Least Concern."','image' => 'images/Alligator.jpg'],
            ['species' => 'Gharial', 'latin' => 'Gavialis gangeticus','category' => 'Reptile', 'content' => 'The gharial is a large, fish-eating crocodile native to the rivers of the Indian subcontinent, particularly the Ganges and Brahmaputra Rivers. Recognizable by its long, narrow snout, which is ideal for catching fish, the gharial can grow up to 6 meters (20 feet) in length. Unlike other crocodiles, it has a specialized diet, primarily feeding on fish, and has fewer interactions with land-based prey. Gharials are excellent swimmers, spending most of their time in water, and have a distinct, bulbous growth on the tip of the male\'s snout used in mating displays. Unfortunately, the gharial is critically endangered due to habitat loss, pollution, and depletion of fish stocks, with only a few hundred individuals remaining in the wild. Conservation efforts are underway to protect this unique species.','image' => 'images/Gharial.jpg'],
            ['species' => 'Iguana', 'latin' => 'Iguana iguana','category' => 'Reptile', 'content' => 'Iguanas are a group of herbivorous lizards belonging to the family Iguanidae, with the most well-known species being the green iguana (Iguana iguana). Native to Central and South America, green iguanas are recognized for their large size, with some individuals growing over 1.5 meters (5 feet) long, including their tail. They have long, spiny crests along their backs and a distinctive dewlap (flap of skin) under their throats. Iguanas are arboreal, spending much of their time in trees, and they are excellent swimmers. As herbivores, they primarily eat leaves, flowers, and fruits. While green iguanas are commonly kept as pets, they face threats in the wild from habitat loss and hunting. Conservation efforts focus on preserving their natural habitats and addressing the challenges posed by invasive species.','image' => 'images/Iguana.jpg'],
            ['species' => 'Horned Lizard', 'latin' => 'Phrynosoma cornutum','category' => 'Reptile', 'content' => 'Horned lizards, also known as "horn toads," are a group of North American reptiles in the family Phrynosomatidae, with the most famous species being the Texas horned lizard (Phrynosoma cornutum). These small, flat-bodied lizards are named for the spiny horns on their heads and their tough, armor-like scales that provide excellent camouflage in their arid, rocky environments. Horned lizards are primarily insectivorous, feeding on ants, beetles, and other small invertebrates. They have unique defense mechanisms, such as puffing up their bodies to appear larger and, in some cases, squirting blood from their eyes as a deterrent to predators. These lizards are important for maintaining insect populations but face threats from habitat destruction, invasive species, and human encroachment, leading to a decline in some populations.','image' => 'images/HornedLizard.jpg'],
            ['species' => 'Gila Monster', 'latin' => 'Heloderma suspectum','category' => 'Reptile', 'content' => 'The Gila monster is a large, venomous lizard native to the southwestern United States and northern Mexico. Recognizable by its stout body, rough scales, and distinctive orange or pinkish patterns on a black background, it is one of the few venomous lizards in the world. Gila monsters are slow-moving, burrowing creatures that spend most of their time in desert habitats, where they primarily feed on eggs, small mammals, birds, and carrion. They have a venomous bite, with saliva containing toxins that can cause pain, swelling, and other symptoms in humans, though bites are rarely fatal. These lizards are known for their ability to store fat in their tails, which helps them survive during periods of food scarcity. While Gila monsters are protected by law in many areas due to habitat loss and their slow reproductive rate, they are not considered endangered.','image' => 'images/GilaMonster.jpg'],
        ]);
    }
}
